name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  IMAGE_NAME: ${{ countries-processing }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Log into ACR
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ACR_ENDPOINT }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: Build and push the Docker image
      uses: actions/checkout@v3
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:$(date +%s)
